package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.38

import (
	"context"
	"fmt"

	"github.com/fidesy-pay/facade/internal/pkg/model"
	crypto_service "github.com/fidesy-pay/facade/pkg/crypto-service"
)

// Balance is the resolver for the balance field.
func (r *queryResolver) Balance(ctx context.Context, filter model.BalanceFilter) (*model.Balance, error) {
	balanceResp, err := r.cryptoServiceClient.GetBalance(ctx, &crypto_service.GetBalanceRequest{
		Address: filter.AddressEq,
		Chain:   filter.ChainEq,
		Token:   filter.TokenEq,
	})
	if err != nil {
		return nil, fmt.Errorf("cryptoServiceClient.GetBalance: %w", err)
	}

	return &model.Balance{
		Balance: balanceResp.GetBalance(),
	}, nil
}
