package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.38

import (
	"context"
	"fmt"
	invoicesservice "github.com/fidesy-pay/facade/internal/pkg/services/invoices-service"

	"github.com/fidesy-pay/facade/internal/pkg/model"
)

// Invoices is the resolver for the invoices field.
func (r *queryResolver) Invoices(ctx context.Context, filter model.InvoicesFilter) (*model.InvoicesPagination, error) {
	invoices, err := r.invoicesService.ListInvoices(ctx, invoicesservice.ListInvoicesFilter{
		IDIn: filter.IDIn,
	})
	if err != nil {
		return nil, fmt.Errorf("invoicesService.ListInvoices: %w", err)
	}

	return &model.InvoicesPagination{
		Items: invoices,
	}, nil
}
