package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.38

import (
	"context"
	"fmt"

	"github.com/fidesy-pay/facade/internal/pkg/model"
)

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.LoginPayload, error) {
	token, err := r.authService.Login(ctx, input)
	if err != nil {
		return nil, fmt.Errorf("authService.Login: %w", err)
	}

	return &model.LoginPayload{
		Token: token,
	}, nil
}
