package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.38

import (
	"context"
	"fmt"
	clients_service "github.com/fidesy-pay/facade/pkg/clients-service"

	"github.com/fidesy-pay/facade/internal/pkg/model"
)

// SignUp is the resolver for the signUp field.
func (r *mutationResolver) SignUp(ctx context.Context, input model.SignUpInput) (*model.SignUpPayload, error) {
	token, err := r.authService.SignUp(ctx, input)
	if err != nil {
		return nil, fmt.Errorf("authService.SignUp: %w", err)
	}

	// TODO Is this a good approach ?
	client, err := r.clientsClient.GetClient(ctx, &clients_service.GetClientRequest{
		Filter: &clients_service.GetClientRequest_Filter{
			UsernameIn: []string{input.Username},
		},
	})
	if err != nil {
		return nil, fmt.Errorf("clientsClient.GetClient: %w", err)
	}

	return &model.SignUpPayload{
		Token:    token,
		ClientID: client.Id,
	}, nil
}
