name: CI/CD Pipeline

on:
  push:
    branches:
      - '*'
      - '!master'

jobs:
  prepare:
    name: Prepare
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get app name
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          REPO_NAME=${{ github.event.repository.name }}
          
          # Check if the branch name is "master"
          if [ $BRANCH_NAME = "master" ]; then
            APP_NAME=$REPO_NAME
          else
            APP_NAME="${REPO_NAME}_${BRANCH_NAME}"
          fi
          
          echo "APP_NAME=$APP_NAME" >> vars.env
          echo $APP_NAME

  clean:
    name: Clean
    runs-on: self-hosted
    needs: prepare
    steps:
      - name: Remove container and image
        run: |
          source vars.env
          
          if docker inspect $APP_NAME > /dev/null 2>&1; then docker rm -f $APP_NAME && docker rmi -f $APP_NAME; else echo "Container not found."; fi

  build:
    name: Build
    runs-on: self-hosted
    needs: clean
    steps:
      - name: Build binary
        run: |
          GOARCH=amd64 GOOS=linux go build -o ./bin/main ./cmd/${{ github.event.repository.name }}

  deploy:
    name: Deploy
    runs-on: self-hosted
    needs: build
    steps:
      - name: Build and run docker container
        run: |
          source vars.env
          
          # generate random ports
          PORT=$((RANDOM % (65000 - 5000 + 1) + 5000))
          
          docker build --tag $APP_NAME .
          
          docker run --name $APP_NAME -d \
            --restart always \
            --network zoo \
            -e APP_NAME=$APP_NAME \
            -e ENV=STAGING \
            -e PORT=$PORT -p $PORT:$PORT \
            -e GRPC_PORT=$((RANDOM % (65000 - 5000 + 1) + 5000)) \
            -e METRICS_PORT=$((RANDOM % (65000 - 5000 + 1) + 5000)) \
             $APP_NAME
          
          echo http://${{ vars.SERVER_HOST }}:$PORT/
          
         
